[package]
name = "tinychain-explorer"
version = "0.1.0"
authors = ["Jennifer Strange <strange.jennifer@yandex.com>"]

[features]
watch = ["handlebars-iron/watch"]

[dependencies]
handlebars-iron = "0.24"
byteorder="1.1"

[dependencies.iron]
version = "*"
